include: package:lint/analysis_options.yaml

analyzer:
  exclude: 
  
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    non_constant_identifier_names: ignore
    avoid_classes_with_only_static_members: ignore
    sized_box_for_whitespace: ignore
    avoid_bool_literals_in_conditional_expressions: ignore